### ISSUE TITLE
Use sh, not bash?

### ISSUE THREAD

**Issue by 130s** [ros-industrial/industrial_ci#125]
I open this as a placeholder for a discussion.

It'd be ideal for all scripts to accommodate more platforms to be run on. 
However, I don't know how critical using `sh` would be though. Even on Windows 10 `bash` runs on these days.

**Comment by ipa-mdl** [comment]
Some features are supported by `sh`, especially the calculations and the `BASH_SOURCE` feature.
we should try to keep compatibility with bash and dash.
(I will add a shellcheck test after the refactoring)

**Comment by ipa-mdl** [comment]
shellcheck compliance and test jobs gets added in #361 
We are using arrays a lot, which are not available in `sh`.

If needed, we could try to migrate the entry script to `sh`, but keep using bash inside Docker.

**Comment by ipa-mdl** [comment]
At this point we cannot switch back to `sh`  anymore.
