### ISSUE TITLE
Deploy build results

### ISSUE THREAD

**Issue by ahoarau** [ros-industrial/industrial_ci#148]
For deployment reasons, it would be great if we could send build results easily from the docker container up to the travis host, so we can take advantage of the ```deploy``` options : 

https://docs.travis-ci.com/user/deployment/releases/

is there a shared folder between the host and the container ?

**Comment by ipa-mdl** [comment]
> is there a shared folder between the host and the container ?

No, not for the normal tests. The prerelease tests share a temporary folder with the host.

> For deployment reasons, it would be great if we could send build results easily from the docker container up to the travis host, so we can take advantage of the deploy options :

We could provide a `$DOCKER_RUN_OPTS` variable that you could use for setting up your volumes, e.g. `DOCKER_RUN_OPTS="-v $HOME/install:/root/catkin_ws/install"`.
Would that suit your needs?

**Comment by ahoarau** [comment]
yes I think that would be perfect. But won't the dir will be deleted after ```source .ci_config/travis.sh```?

**Comment by ipa-mdl** [comment]
> But won't the dir will be deleted after source .ci_config/travis.sh?

No, it should persist.

**Comment by ipa-mdl** [comment]
please try #149

**Comment by ahoarau** [comment]
Trying now, thanks !

**Comment by ahoarau** [comment]
I'm getting this now : 
```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[clean] Removing installspace: /root/catkin_ws/install
[clean] Failed to clean profile `default`
[clean] Note: Parts of the workspace have been cleaned which will necessitate re-configuring CMake on the next build.
```

**Comment by ipa-mdl** [comment]
I guess the clean command tries to remove the install folder.
Please try https://github.com/ros-industrial/industrial_ci/pull/150 it does no need clean anymore.

**Comment by ahoarau** [comment]
:+1: builds fine now

**Comment by ahoarau** [comment]
It builds fine, but the result seems empty ! 

```
The command "source .ci_config/travis.sh" exited with 0.
 ls $HOME/install

The command "ls $HOME/install" exited with 0.
```

**Comment by ipa-mdl** [comment]
#150 did not include #149 
I have rebased it, please try again.
My local test (with `run_ci`) worked :)

**Comment by ahoarau** [comment]
working ! awesome thanks !

**Comment by ipa-mdl** [comment]
I will close this one as #150 was merged.
Please do not forget to switch back to master :D

**Comment by ahoarau** [comment]
Excellent ! Thank you
