### ISSUE TITLE
add ccache

### ISSUE THREAD

**Issue by ahoarau** [ros-industrial/industrial_ci#153]
This would save us a lot of time when it's recompiling for the tests.

```apt install ccache```
and then
```export CXX='ccache g++' CC='ccache gcc' ```

what do you think ?

**Comment by ipa-mdl** [comment]
> it's recompiling for the tests.

We will get rid of the recompiling in #150 

However, we should pass `CC` and `CXX`to docker. This way we could test for different compilers.

**Comment by ipa-mdl** [comment]
You can now pass `CC` and `CXX`, and ccache could be installed with `ADDITIONAL_DEBS`

**Comment by ahoarau** [comment]
excellent, but then not ccache not really useful now thanks to #150 !

**Comment by ipa-mdl** [comment]
explicit `ccache` support gets added in #182
