### ISSUE TITLE
License of the package

### ISSUE THREAD

**Issue by 130s** [ros-industrial/industrial_ci#17]
I thought I would change the license in a trial to conform ROS-I recommendation (apache 2.0), but the repository I got much inspiration from (`jsk_travis`) is BSD (and some scripts from there are simply redistributed here), I like to hold back.

If there's any other opinions, please reopen and discuss.

**Comment by 130s** [comment]
Just happened to find [Apache2.0 LICENSE file](https://github.com/ros-industrial/industrial_ci/blob/master/LICENSE), which Shaun created when he initiated this repo. I/we gotta figure out what license we use.

**Comment by gavanderhoorn** [comment]
IANAL, but AFAIK, you can relicense artefacts, but you'll have to get permission from the original authors.

Also: it's not a requirement to have all artefacts under the same license. It's perfectly possible for some bits to be BSD, with others under Apache 2. And apparently BSD and Apache 2 are very compatible with each other.

Perhaps @ipa-mirb can refer us to some relevant documents?

**Comment by shaun-edwards** [comment]
I have the same understanding as @gavanderhoorn.  I would propose that we keep existing licenses as is and require that any new "code" be licensed under Apache 2.0

**Comment by ipa-mirb** [comment]
Unfortunately I do not have specific documents to point you to, as last time we dealt with licensing at the "OSS - legal aspects" event here at IPA we discussed more general terms. But from what I understood mixing BSD and Apache should not be a problem (whereas e.g., LGPL and BSD could be, I am afraid).

**Comment by 130s** [comment]
As I noted in https://github.com/ros-industrial/industrial_ci/pull/108#issuecomment-274114279, now there are only files that were created within this repo so that we have full control of the license for this package/repo (INAL but I hope so). So in https://github.com/ros-industrial/industrial_ci/pull/113 I changed the package license to Apache 2.0.
