### ISSUE TITLE
Enable Travis' cron job

### ISSUE THREAD

**Issue by 130s** [ros-industrial/industrial_ci#173]
Suggested by @ipa-mdl in the offline conversation.

+1 from me to enable it on this repo, and also recommend users (via mailinglist?) to enable it.

**Comment by ipa-mdl** [comment]
Weekly or daily?

Daily would help to detect problems with our downstream dependencies earlier, but blocks build slots for the ´ros-indusstrial` organization, but I guess cron jobs will be exeucated on idle times.

**Comment by ahoarau** [comment]
Going with nightly builds can't be bad for business 👍

**Comment by ipa-mdl** [comment]
I have set-up a daily cron-job on master.
![image](https://cloud.githubusercontent.com/assets/727227/25844335/654a74dc-34aa-11e7-8421-216904243082.png)

Let's try this for a couple of days :)

**Comment by ipa-mdl** [comment]
cron jpbs are up and running.
