### ISSUE TITLE
Cache compiled code with ccache

### ISSUE THREAD

**Issue by VictorLamoine** [ros-industrial/industrial_ci#181]
The cache is saved/restored and allows faster builds.
Very useful for big projects!

https://gitlab.com/VictorLamoine/ros_gitlab_ci/blob/master/ccache.bash
https://gitlab.com/VictorLamoine/ros_gitlab_ci/blob/master/.gitlab-ci.yml#L10-12

I'm pretty sure you can do the same with Travis CI.

**Comment by ipa-mdl** [comment]
Thanks for pointing this out!

> I'm pretty sure you can do the same with Travis CI.

Wasn't too complicated: https://github.com/ipa-mdl/ros_canopen/blob/ccache/.travis.yml#L14
It saved 2 out of 6 minutes for `ros_canopen`.
After 2nd run: https://travis-ci.org/ipa-mdl/ros_canopen/builds/244099816

Right now I am not sure if we should just document this use case or even implement a `USE_CCACHE` flag.

**Comment by ipa-mdl** [comment]
> Right now I am not sure if we should just document this use case or even implement a USE_CCACHE flag.

I have implemented a [feature](https://github.com/ipa-mdl/industrial_ci/tree/ccache) based on `CCACHE_DIR`, which integrates nicely with travis.
PR will follow as soon as travis backlosg is back to normal (4k jobs queued at the moment).

**Comment by VictorLamoine** [comment]
Looks good :)

**Comment by 130s** [comment]
Addressed in #182
