### ISSUE TITLE
Build fails if no .rosinstall file is present

### ISSUE THREAD

**Issue by ipa-lth** [ros-industrial/industrial_ci#194]
We might declare a rosinstall file to be necessary, but my personal opinion is, that if there is no rosinstall file, it should not install anything and just continue.
What is your opinion on this?

**Comment by ipa-mdl** [comment]
> What is your opinion on this?

If a configuration is invalid, the build should fail,
e.g. to detect that someone forgot to commit the rosinstall file.

You could place an empty file in your repository.

**Comment by ipa-lth** [comment]
I might missed it, but if you are consider a working repository (without the need for a rosinstall file) invalid, your README should be updated what valid means. In fact, I can just ask you, but someone else might cannot...

**Comment by ipa-mdl** [comment]
> I might missed it, but if you are consider a working repository (without the need for a rosinstall file) invalid

If you don't need a rosinstall file, just keep the default `UPSTREAM_WORKSPACE=debian`.

https://github.com/ros-industrial/industrial_ci/issues/147 is related.

**Comment by ipa-mdl** [comment]
@ipa-lth: Can we close this?

**Comment by ipa-mdl** [comment]
It turned out that in an (outdated?) example `UPSTREAM_WORKSPACE=file` was included, which fails if no rosinstall file is present.
However, `UPSTREAM_WORKSPACE` can be omitted safely in this case.
