### ISSUE TITLE
Bad OS_CODE_NAME deduction from DOCKER_BASE_IMAGE

### ISSUE THREAD

**Issue by miguelprada** [ros-industrial/industrial_ci#197]
I've been having a lot of issues troubleshooting some errors and finally I've figured out that my problems came from the [automatic deduction of `OS_CODE_NAME` from the `DOCKER_BASE_IMAGE` tag](https://github.com/ros-industrial/industrial_ci/blob/c371892602e0e0af3f4abd5cf4b0e11d83badbc9/industrial_ci/src/env.sh#L78) when this option is used.

The tag of the image I was using was `base` and therefore the [ROS repository configuration](https://github.com/ros-industrial/industrial_ci/blob/c371892602e0e0af3f4abd5cf4b0e11d83badbc9/industrial_ci/src/docker.sh#L179) was completely wrong.

This can be fixed by making sure to specify `OS_CODE_NAME` in addition to `DOCKER_BASE_IMAGE`, but maybe some warning should be added somewhere in the docs.

The prerelease tests may also suffer from this since `OS_NAME` will also be nonsense, but I'm not familiar whith these at all...

**Comment by ipa-mdl** [comment]
I have exposed `DOCKER_BASE_IMAGE` without a concrete use case in mind..
Looks like the automatic detection might harm more than it helps then.

I see two possibilities:
1. don't deduce it and issue an error
2. try to read it from lsb_release, if not sepcified explicitly

I will try to go for option 2.

> The prerelease tests may also suffer from this since OS_NAME will also be nonsense, but I'm not familiar whith these at all...

Yes, it's the same there. `lsb_release` won't help, so it should be read from the env.
