### ISSUE TITLE
[docker-in-docker] Location of script files for {BEFORE, AFTER}_SCRIPT

### ISSUE THREAD

**Issue by 130s** [ros-industrial/industrial_ci#217]
I think the [usage of `{BEFORE, AFTER}_SCRIPT`](https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#run-pre-post-process-custom-commands) was written before we introduced Docker-in-Docker and thus outdated. Now I get `bash: %SCRIPTNAME%: command not found` error (e.g. [in this line](https://travis-ci.org/ros-industrial/industrial_calibration/jobs/278522903#L597) for [this PR](https://github.com/ros-industrial/industrial_calibration/pull/112), particularly [this commit](https://github.com/ros-industrial/industrial_calibration/pull/112/commits/536014b84bdcc078d009eaa2982e2ca624533c94), unless I'm doing something wrong there). 

What the right path of the scripts to pass to these variables?

**Comment by ipa-mdl** [comment]
Please try `./.travis_ceres.sh`, otherwise it get looked up in `PATH`.

**Comment by 130s** [comment]
Ah...that was my carelessness. Doc specifies `./%SCRIPT%` path. Thanks.
