### ISSUE TITLE
Passing custom environment variable to Docker images

### ISSUE THREAD

**Issue by 130s** [ros-industrial/industrial_ci#233]
Is there a way to pass custom variables than what's defined in [docker.env](https://github.com/ros-industrial/industrial_ci/blob/master/industrial_ci/src/docker.env)?

I want this variable to be available on Docker as early as possible, so `BEFORE_SCRIPT` may not suffice.

**Comment by ipa-mdl** [comment]
`DOCKER_RUN_OPTS='-e MY_VARIABLE_NAME'` should do the trick.
You can even set it to a specific value: `DOCKER_RUN_OPTS='-e ANSWER=42'`.

**Comment by 130s** [comment]
@ipa-mdl Thank you for the quick response.
Documented in https://github.com/ros-industrial/industrial_ci/pull/234 (in addition to its brief variable description).
