### ISSUE TITLE
[Travis] Invalid SSH keys/config for wstool update

### ISSUE THREAD

**Issue by ipa-jba** [ros-industrial/industrial_ci#247]
To fix the error ocurring since the latest update of travis I had to change the permissions of the .ssh folder.

See: https://github.com/ipa-jba/industrial_ci/commit/3cb5be401afac22d76388bd14f71719002f7d58e

However if this is a good solution is up for disussion.

@ipa-fxm @ipa-mdl

**Comment by ipa-mdl** [comment]
I think this is unrelated to the new travis image, but might be an issue with the new docker version.
`docker cp` used to create files as root, but this seems to have changed.

This new version broke some other things (not related to `industrial_ci`) for me as well.

**Comment by ipa-mdl** [comment]
Looks like a [bug](https://github.com/moby/moby/issues/34096) in docker.

**Comment by ipa-mdl** [comment]
A fix for docker was [proposed](https://github.com/moby/moby/pull/35874).

**Comment by ipa-mdl** [comment]
I guess this issue was resolved.
