### ISSUE TITLE
Error "docker.sh: line 138: docker: command not found"

### ISSUE THREAD

**Issue by jihoonl** [ros-industrial/industrial_ci#254]
I am experiencing industrial_ci travis job failure in [web_video_server](https://github.com/RobotWebTools/web_video_server). Do you have any insight why it is failing?

* [Configuration](https://github.com/RobotWebTools/web_video_server/blob/develop/.travis.yml)
* [Log](https://travis-ci.org/RobotWebTools/web_video_server/jobs/323669365)

**Comment by 130s** [comment]
(Updated title to describe the issue better)

The direct cause of failure is that [`docker` is not available](https://travis-ci.org/RobotWebTools/web_video_server/jobs/323669365#L174). Looks like the job passed [a month ago](https://travis-ci.org/RobotWebTools/web_video_server/jobs/304806570).

I don't know why, but [apt-get failed to access many sites for retrieving updates](https://travis-ci.org/RobotWebTools/web_video_server/jobs/323669365#L105). As an easy-slacker attempt, I'm curious to see if restarting the same job fixes this or not.

**Comment by jihoonl** [comment]
not sure.. I tried multiple times and confirmed that the problem persists.

**Comment by ipa-mdl** [comment]
Duplicate of #167, your config is not valid..
Please set `dist: trusty`.

**Comment by jihoonl** [comment]
Ok. thanks it works.

**Comment by ipa-mdl** [comment]
This seems to confuse a number of users.

**Comment by ipa-mdl** [comment]
> Please set dist: trusty.

This can be removed now.
Travis is already using `trusty` per default and will soon migrate to `xenial`.
