### ISSUE TITLE
rosdep install searches /root/catkin_ws, so "install" space is included if it exists

### ISSUE THREAD

**Issue by 130s** [ros-industrial/industrial_ci#257]
Using a very custom Docker image where the packages are built into `devel` and `install` directories, `rosdep` fails complaining there are multiple packages with the same name.

```
:
++ rosdep_opts=(-q --from-paths $CATKIN_WORKSPACE --ignore-src --rosdistro $ROS_DISTRO -y)
++ '[' -n '' ']'
++ set -o pipefail
++ grep 'executing command'
++ rosdep install -q --from-paths /root/catkin_ws --ignore-src --rosdistro indigo -y

ERROR: Rosdep experienced an error: Multiple packages found with the same name "pkg_AA":
- install/share/pkg_AA
- src/org_X/repo_Y/pkg_AA
Multiple packages found with the same name "pkg_BB":
- install/share/pkg_BB
- src/org_X/repo_Y/pkg_BB
:
```
This is easily worked around by removing the devel and install in the Docker image. But wouldn't it be nicer if `rosdep` only searches `/root/catkin_ws/src`?

**Comment by ipa-mdl** [comment]
Yes, src is enough.
Please go ahead and provide a fix :)
