### ISSUE TITLE
Add support for python3

### ISSUE THREAD

**Issue by ipa-mdl** [ros-industrial/industrial_ci#274]
We should introduce a flag `PYTHON_VERSION` (?) that switches to the `python3` debians.

Some questions:
* Are additonal steps needed for python3 testing?
* Should we provide docker images for python3?

**Comment by 130s** [comment]
Just a food for thought; [`rospkg` runs tests on CI against multiple Python versions](https://github.com/ros-infrastructure/rospkg/blob/5e55690e197411c29735632d3628e0b5ca6d6803/.travis.yml).

**Comment by ipa-mdl** [comment]
`master` uses python3 for ROS2.
I don't know what's the status of ROS1 and python3, I guess it is targeted for `noetic`.

**Comment by 130s** [comment]
> I guess it is targeted for `noetic`.

Verified that seems to be the case.
- Melodic supports 2.7 (testing against 3.5 is recommended) [from REP0003](https://www.ros.org/reps/rep-0003.html#melodic-morenia-may-2018-may-2023).
- A set of [tutorial for transitioning to Python3 is recently started by OR on ROS wiki](http://wiki.ros.org/UsingPython3).

The tutorial above identifies a few areas that might need changes. Honestly I've never thought about Py3 transition, but I'm afraid there would be a lot of issues than I thought. Hope that won't be the case, but starting to provide CI environment earlier might be helpful for catching issues early? OR already opened up Jenkins job http://wiki.ros.org/UsingPython3/Contributing#Check_the_Noetic_CI_jobs for capturing issues early (although I'm struggling how to interpret its result).

**Comment by ipa-mdl** [comment]
> Melodic supports 2.7 (testing against 3.5 is recommended) from REP0003.

But how to test? And how to tell rosdep?

**Comment by ipa-mdl** [comment]
> But how to test? And how to tell rosdep?

I was able to figue it out, I guess ;)
#429 is based on http://wiki.ros.org/UsingPython3/BuildUsingPython3

I will have a look at the new Noetic CI jobs later

**Comment by ipa-mdl** [comment]
Noetic support was merged: #499

**Comment by ipa-mdl** [comment]
Python 3 is supporedt for ROS1 noetic and ROS2.
Proper support for ROS1 melodic is very hard to implement and most-likely not needed (anymore).
