### ISSUE TITLE
Source workspace after build and before tests?

### ISSUE THREAD

**Issue by peci1** [ros-industrial/industrial_ci#289]
In my tests, I use rospack to find path to some resources, but sometimes the tests fail because the newly built workspace is not yet sourced. 

Do you think adding the sourcing right before test runs is okay?

**Comment by ipa-mdl** [comment]
`rospack` should work without it. Can you provide an example? (Code, errors logs, etc.)

Sourcing the workspace is not that easy, some repos use `install` space, others use `devel` space.
In addtion sourcing might hide problems with missing test dependencies etc.

**Comment by peci1** [comment]
Hmm, I probably don't understand how should it work.

In a test in package `tensorflow_ros_test`, I'm calling

    std::string model_path = ros::package::getPath("tensorflow_ros_test") + "/models/train.pb";

How would rospack now about this package when the space hasn't been sourced?

**Comment by ipa-mdl** [comment]
Are you running this wrapped in a `rostest`  or just `gtest`.
I guess the environment variables are only present in `rostest`.

**Comment by peci1** [comment]
I'm running plain gtest. You're right that in rostest the environment should be set up for roslaunch to find the package... I didn't know it's done any other way than sourcing the devel/install space...

So would it be possible to e.g. add something like `before_script`, but which is run after building and before running the tests? Then the users could choose what's the best way to source the workspace.

**Comment by ipa-mdl** [comment]
I would suggest to wrap it in `rostest`. This ensures that the environment is set-up correctly for all cases.

> So would it be possible to e.g. add something like before_script, but which is run after building and before running the tests? Then the users could choose what's the best way to source the workspace.

These scripts cannot change the environment. So enable this we would need to source them, and this would be way too error-prone.

**Comment by peci1** [comment]
That would be a solution. I'm just still curious about one thing - why [sourcing install space](https://github.com/ros-industrial/industrial_ci/blob/d375a781f6f7ffdfb71e0abb4e4a47e0be309bd1/industrial_ci/src/tests/source_tests.sh#L231) is okay, but [devel space is not sourced](https://github.com/ros-industrial/industrial_ci/blob/d375a781f6f7ffdfb71e0abb4e4a47e0be309bd1/industrial_ci/src/tests/source_tests.sh#L197).

Could something like this work?

    $CATKIN_WORKSPACE/devel/env.sh  catkin build --no-deps --catkin-make-args run_tests  ...

**Comment by ipa-mdl** [comment]
By default we are using the install space only.

**Comment by ipa-mdl** [comment]
>  why sourcing install space is okay

This code is only executed for *.test files in install space. We need the env loader because the env won't be  set-up automatically (like `run_test`  would do).

**Comment by peci1** [comment]
Thanks for the insight.

I started digging deeper then to see why unit tests would be run with the sourced environment and rostests would not, and my conclusion is that any kind of test is run using `env.sh` when calling `make run_tests`. But that's only for devel space. My investigation is the following: (correct me if I'm wrong):

 - both normal unit tests and rostests [are run when calling `make run_tests`](http://wiki.ros.org/rostest/Writing#Running_your_rostest_with_.27make_run_tests.27)
 - `add_rostest` [calls](https://github.com/ros/ros_comm/blob/e5cdde3414b0556d395a2b9cf321933c3f63e1cb/tools/rostest/cmake/rostest-extras.cmake.em#L57) `catkin_run_tests_target`
 - `catkin_run_tests_target` [calls](https://github.com/ros/catkin/blob/643efa7db49d4c9faabacb53607703acd0d229f3/cmake/test/tests.cmake#L123) the `run_tests.py` using a `CATKIN_ENV` wrapper
 - `CATKIN_ENV` is set to `build/catkin_generated/env_cached.sh`, which changes the environment in the same way `devel/env.sh` does
 - there is no Make target for calling the tests from install space

Concluding, I think this issue was just a misunderstanding from my side (and probably some unrelated error), because all tests and rostests run from the devel space should automatically be run in the correct (devel) environment. And I also understand why it is needed to source `install/env.sh` to run the tests in install space (because there's no Make target that would do it).
