### ISSUE TITLE
Debian jessie test job is broken

### ISSUE THREAD

**Issue by ipa-mdl** [ros-industrial/industrial_ci#291]
Not sure why, but the [job](https://travis-ci.org/ros-industrial/industrial_ci/jobs/393297493) fails with
> ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
industrial_ci: No definition of [catkin] for OS [debian]

**Comment by ipa-mdl** [comment]
The change was introduced in https://github.com/ros/rosdistro/pull/18151.
If this does not get resolved, we have to drop support for jessie.

**Comment by 130s** [comment]
@ipa-mdl Some open PRs should pass CI now that this is closed?
