### ISSUE TITLE
Defined but empty  'DOCKER_IMAGE' does not cause error.

### ISSUE THREAD

**Issue by 130s** [ros-industrial/industrial_ci#296]
When passing empty `DOCKER_IMAGE` variable, CI continues although the intended docker image wasn't pulled. This makes debugging harder.

**Comment by ipa-mdl** [comment]
Can you give more context, please?
`DOCKER_IMAGE`  has multiple purposes, it might be used differently with regard to other settings.
In addition it would be good to know what the error looks like.

**Comment by ipa-mdl** [comment]
I see.
This case should be fixed [here](https://github.com/ros-industrial/industrial_ci/blob/d66bf0f1578008c23f0673ff8894e20308f067c0/industrial_ci/src/docker.sh#L167), because it just tests the length..

**Comment by machinekoder** [comment]
Working on this for #wrid18

**Comment by 130s** [comment]
Maybe related to #212 btw.

**Comment by ipa-mdl** [comment]
#212 is not related.

**Comment by 130s** [comment]
> #212 is not related.

You're right (I'm blaming my bad view on github from cellphone :/ ).

**Comment by ipa-mdl** [comment]
Reviewing this issue, I would now opt for "wont fix".
`DOCKER_IMAGE=''` was not handled as error, because it means "use the default".
If we check this, then we have to a lot more variables.
