### ISSUE TITLE
Cannot skip rosdep step

### ISSUE THREAD

**Issue by machinekoder** [ros-industrial/industrial_ci#306]
In some cases, e.g. when using an already prepared Docker image, we can skip the `rosdep install` step. This is especially useful when our dependencies aren't released yet.

**Comment by machinekoder** [comment]
Alternatively, overwriting the `rosdep` command would also help. Moreover, it may be useful to execute the `wstool init` step before the `rosdep` step, since this might add additional dependencies.

**Comment by machinekoder** [comment]
Ignore my last statement, `wstool` is executed before the `rosdep install` step.

**Comment by machinekoder** [comment]
I think `rosdep` is missing the `--os=debian:stretch` option.

**Comment by ipa-mdl** [comment]
> In some cases, e.g. when using an already prepared Docker image, we can skip the rosdep install step. This is especially useful when our dependencies aren't released yet.

Why do you want to skip rosdep in this case?
In addition to installing them, `rosdep` checks that the dependencies exist and can be resolved.
However, I could imagine to skip `rosdep update`.

> I think rosdep is missing the --os=debian:stretch option.

rosdep auto-detects the OS. You could override the detection by setting `ROS_OS_OVERRIDE`.

**Comment by machinekoder** [comment]
Then the OS autodetection does not work correctly. It looks for `stretch` rather than `debian:stretch`. The rosdep works perfectly fine when passing `--os` manually.

**Comment by ipa-mdl** [comment]
If rosdep fails to detect Debian stretch, this should better be fix in `rosdep`/`rospkg`.
Which error do you get?

**Comment by machinekoder** [comment]
I'm doing something wrong, I did not specify `UPSTREAM_WORKSPACE` to select a file for the `.rosinstall`.
