### ISSUE TITLE
[doc] Clarify BUILD_PKGS_WHITELIST, TARGET_PKGS, PKGS_DOWNSTREAM

### ISSUE THREAD

**Issue by 130s** [ros-industrial/industrial_ci#315]
Using some variables such as `BUILD_PKGS_WHITELIST, TARGET_PKGS, PKGS_DOWNSTREAM`, you can specify the role of packages. For some usecases, it's not clear from the document how to use these variables is the best. It's not even clear from what I understand the code, so we may or may not change the logic.

Some things to be clarified:

- [ ] Do they get consolidated? I've done a test below, using [this line](https://github.com/ros-industrial/industrial_ci/blob/d8ac9340ab52a2fc625a55d558759831a3a79b4b/industrial_ci/src/tests/source_tests.sh#L177) locally, but these variables don't seem to get merged. 

  ```
  $ PKGS_DOWNSTREAM=pkg_downstream
  $ if [ "${PKGS_DOWNSTREAM// }" == "" ]; then export PKGS_DOWNSTREAM=$( [ "${BUILD_PKGS_WHITELIST// }" == "" ] && echo "$TARGET_PKGS" || echo "$BUILD_PKGS_WHITELIST"); fi
  $ echo $PKGS_DOWNSTREAM
  pkg_downstream
  $ TARGET_PKGS=pkg_target
  $ if [ "${PKGS_DOWNSTREAM// }" == "" ]; then export PKGS_DOWNSTREAM=$( [ "${BUILD_PKGS_WHITELIST// }" == "" ] && echo "$TARGET_PKGS" || echo "$BUILD_PKGS_WHITELIST"); fi
  $ echo $PKGS_DOWNSTREAM
  pkg_downstream
  $ echo $TARGET_PKGS 
  pkg_target
  $ echo $BUILD_PKGS_WHITELIST
  
  $ BUILD_PKGS_WHITELIST=pkg_whitelist
  $ echo $BUILD_PKGS_WHITELIST
  pkg_whitelist
  $ echo $TARGET_PKGS 
  pkg_target
  $ echo $PKGS_DOWNSTREAM
  pkg_downstream
  ```
  - Or maybe just the logic needs to updated to consolidate these variables when they are defined with non-empty values?
- [ ] What's the best way to pass packages to multiple of these variables (considering they don't get consolidated)? E.g. When you want to test a `pkg_target` in the target repo and also `pkg_downstream` from a downstream repo, I think you want to pass pkg_target to `TARGET_PKGS ` and pkg_downstream to `PKGS_DOWNSTREAM`.

**Comment by ipa-mdl** [comment]
I just removed them in #361
