### ISSUE TITLE
Option to access to Docker image built inside industrial_ci

### ISSUE THREAD

**Issue by 130s** [ros-industrial/industrial_ci#318]
@ipa-mdl Is there any reason why there is no way to access the docker image built during industrial_ci process?

I see in a recent change there's an option to `docker commit` the built image https://github.com/ros-industrial/industrial_ci/blob/d8ac9340ab52a2fc625a55d558759831a3a79b4b/industrial_ci/src/docker.sh#L114, but the option is not publicly exposed (only available when running `rerun_ci` script AFAIUC). And regardless of which option to start industrial_ci, the built image is deleted https://github.com/ros-industrial/industrial_ci/blob/d8ac9340ab52a2fc625a55d558759831a3a79b4b/industrial_ci/src/docker.sh#L116.

If there's no problem, I'm interested in adding a generic option to get an access to the built image.

In my usecase, I want to store Docker images with the latest code. To achieve that currently I have CI jobs that run `docker build`, separately from industrial_ci jobs. While that works ok, since in industrial_ci an image is already built I'm interested in re-using what's already built by industrial_ci. That allows to use the same image for testing on CI and for the future purpose, and also save some CI time (it's non-trivial for a private repo on a hosting service). It could also allow a usecase where the update gets deployed by container (common in web app world, but it's possible in robotics as well).

CC @AustinDeric

**Comment by ipa-mdl** [comment]
> Is there any reason why there is no way to access the docker image built during industrial_ci process?
I see in a recent change there's an option to docker commit the built image

Yes, #279 was merged while it still was WIP.

> but the option is not publicly exposed (only available when running rerun_ci script AFAIUC).

https://github.com/ros-industrial/industrial_ci/pull/279#issuecomment-396168104

Just rename `_COMMIT_IMAGE` (and perhaps `_COMMIT_IMAGE_MSG`) and add documentation.

**Comment by AustinDeric** [comment]
@ipa-mdl 
> The container gets deleted, but not the image.
I cannot find the image that gets built by industrial CI. i run `docker images` after the industrial ci  script and it doesn't return the recently built image:
```
  after_script:
    - docker images
```
Furthermore, looking at the build logs, the last command is `docker rm` and i do not see a commit of the image.

**Comment by ipa-mdl** [comment]
The commit will only happen if `_COMMIT_IMAGE` is set.

**Comment by 130s** [comment]
Addressed by #319
