### ISSUE TITLE
ABI check feature failing without obvious output but "ERROR: no symbols info in the ABI dump"

### ISSUE THREAD

**Issue by 130s** [ros-industrial/industrial_ci#322]
Of [this PR](https://github.com/ros-drivers/openni2_camera/pull/89), ABI check failed e.g. https://travis-ci.org/ros-drivers/openni2_camera/jobs/437001338
```
Preparing, please wait ...
ERROR: no symbols info in the ABI dump
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Function abi_check_libopenni2_camera_nodelet returned with code '7' after 0 min 0 sec 
```
But other than that I failed to find the root cause of the error. There's a lot of warnings during the previous ABI check steps, but I don't see anything obviously failing.

**Comment by 130s** [comment]
Looks like error code 7 is `Invalid input ABI dump` according to the [abi-compliance-checker's doc](https://lvc.github.io/abi-compliance-checker/#Error).

**Comment by ipa-mdl** [comment]
The big question is: Why is the ABI dump empty?
The build shows a lot of warnings.

I would suggest to test it locally and bind-mount the directories. This way you can introspect the results.
Or we could output the dump if the exit code is > 1.

**Comment by ipa-mdl** [comment]
How is this different from https://github.com/ros-industrial/industrial_ci/issues/258?
