### ISSUE TITLE
Builds always succeeding

### ISSUE THREAD

**Issue by gerardcanal** [ros-industrial/industrial_ci#325]
I have noticed that my builds are succeeding even though they failed to compile, I guess it may be because of 69430dc7a2a10d4aa3bc59f26246288146420b74, as this was not happening last week. 

An example:
![image](https://user-images.githubusercontent.com/5610438/47711505-4db2c280-dc2d-11e8-8c1b-15c9bcc0128a.png)

**Comment by ipa-mdl** [comment]
Thanks for reporting!
I will push a fix ASAP.

**Comment by ipa-mdl** [comment]
Please test again.

**Comment by gerardcanal** [comment]
That was fast! It looks like it's fixed now!

Rebuild of the same commit:
![image](https://user-images.githubusercontent.com/5610438/47717203-09c7b980-dc3d-11e8-814a-bb0220d65d43.png)

Thank you!
