### ISSUE TITLE
Travis CI now has Xenial support (nov '18)

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/industrial_ci#354]
You've probably seen it ([blog](https://blog.travis-ci.com/2018-11-08-xenial-release)).

Since `industrial_ci` uses Docker for most of the work, any benefits of updating configurations to use the new `dist`?

---

Edit: link to docs: [The Xenial Build Environment](https://docs.travis-ci.com/user/reference/xenial).

**Comment by ipa-mdl** [comment]
I ran some [tests](https://github.com/ipa-mdl/industrial_ci/tree/xenial), but I could [not see](https://travis-ci.org/ipa-mdl/industrial_ci/builds/474806692) any significant changes.

Trusty will be EOL in April..
For now I would recommend to not set `dist` at all, but to require  the [docker service](https://github.com/ros-industrial/industrial_ci/blob/master/doc/.travis.yml) and let Travis decide.
