### ISSUE TITLE
vsctool support

### ISSUE THREAD

**Issue by amc-nu** [ros-industrial/industrial_ci#357]
Is there any way to execute [`vcstool`](https://github.com/dirk-thomas/vcstool) to get all the repositories just after `git clone`? For a repository of the https://github.com/ros2/ros2 style.

**Comment by ipa-mdl** [comment]
It is supported in [my colcon branch](https://github.com/ipa-mdl/industrial_ci/tree/colcon).

**Comment by amc-nu** [comment]
Awesome! Thanks for the prompt reply!
