### ISSUE TITLE
Update repository key / URLs

### ISSUE THREAD

**Issue by ipa-mdl** [ros-industrial/industrial_ci#371]
Keep track of https://discourse.ros.org/t/security-issue-on-ros-build-farm/9342 and update key/URLs as soon as the new repository is ready

**Comment by ipa-mdl** [comment]
legacy branch was fixed in #373, #378 is still pending

**Comment by MoriKen254** [comment]
@ipa-mdl thanks, https://github.com/ros-industrial/industrial_ci/issues/377 helped us a lot ;)

**Comment by ipa-mdl** [comment]
This can be closed with #378 and the corresponding patch for the new version.

**Comment by ipa-mdl** [comment]
fixed in #373, #378, #392, #393 (and #361)
