### ISSUE TITLE
Test colcon-ready version

### ISSUE THREAD

**Issue by ipa-mdl** [ros-industrial/industrial_ci#390]
Test #361 with as many respositories as possible.

Just replace
```
 git clone --quiet --depth 1 https://github.com/ipa-mdl/industrial_ci.git .industrial_ci -b colcon-rebase
```

- [x] https://github.com/ros-controls/control_msgs (crystal-devel)
- [x] https://github.com/ros-controls * 
- [x] https://github.com/ros-industrial *

**Comment by miguelprada** [comment]
I edited your comment, since there was a typo in the branch name `colcon-rebased` -> `colcon_rebase`.

**Comment by ipa-mdl** [comment]
All tests passed. I will updated them after #361 was merged.

**Comment by ipa-mdl** [comment]
updated all PRs, all green.
