### ISSUE TITLE
Running locally fails if docker was installed via snap?

### ISSUE THREAD

**Issue by agutenkunst** [ros-industrial/industrial_ci#409]
Running industrial_ci locally failed with
```
docker command not found
```
when I had docker installed via snap. Via apt works fine now...

Can anyone reproduce?

**Comment by ipa-mdl** [comment]
I did not yet use snap to install Docker.
(In the beginning it only shipped a version outdated version, )

> Running industrial_ci locally failed with

How do you run it locally? `run_ci`?
Running industrial_ci locally failed with

**Comment by agutenkunst** [comment]
> How do you run it locally? `run_ci`?

run_travis

**Comment by ipa-mdl** [comment]
I can confirm this issue.
In this case docker gets installed to `/snap/bin`, which is not in the default `PATH`.
Passing the user settings (#411) fixes it.

**Comment by agutenkunst** [comment]
Closed by #411 .
