### ISSUE TITLE
Needs false-positive detection

### ISSUE THREAD

**Issue by 130s** [ros-industrial/industrial_ci#41]
For example in https://github.com/ros-industrial/industrial_ci/issues/39 jobs didn't reach the end of travis.sh script but passed without emitting errors.

**Comment by 130s** [comment]
When https://github.com/ros-industrial/industrial_ci/pull/80 gets completed this can probably be closed.

**Comment by ipa-mdl** [comment]
This is available with `EXPECT_EXIT_CODE`.
