### ISSUE TITLE
Verbose output during during target workspace build

### ISSUE THREAD

**Issue by tylerjw** [ros-industrial/industrial_ci#467]
I would like to enable verbose catkin build during the target workspace build but not the upstream build.  Is there an easy way to do this with gitlab builds?

**Comment by ipa-mdl** [comment]
You can set `VERBOSE_OUTPUT=true` (or `VERBOSE_OUTPUT: true`, depending on your actual syntax).
All options are listed in the documentation: [legacy](https://github.com/ros-industrial/industrial_ci/blob/legacy/doc/index.rst#optional-environment-variables)/[master](https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#optional-environment-variables)
