### ISSUE TITLE
rosdep not finding packages in subfolders

### ISSUE THREAD

**Issue by tianshiz** [ros-industrial/industrial_ci#483]
In my catkin workspace I have the following:
```
-src
 --zed-ros-wrapper
 ---README.md
 ---zed_wrapper
```

when running this CI on pipelins it tells me that 
`Cannot locate rosdep definition for "zed_wrapper"`

This workspace config builds fine in my test docker image, I have no idea why it's failing here. Is it because zed_wrapper is a package within a folder and not directly under ws/src?

**Comment by ipa-mdl** [comment]
Hard to tell without code.

> This workspace config builds fine in my test docker image,

How do you my build the docker image?

> Is it because zed_wrapper is a package within a folder and not directly under ws/src?

No, this is not a problem at all.

**Comment by tianshiz** [comment]
i think my problem is different now. It's actually because I'm building some external git repos in the same workspace. These git repos aren't being pulled from my main repo in Pipelines. Thus rosdep finds that they are missing.

**Comment by ipa-mdl** [comment]
> How do I add those external git repos?

In the legacy version of `industrial_ci`, you would need to list in a rosinstall file.
The master  version has more options: https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#workspace-management

**Comment by tianshiz** [comment]
Is it possible to have more than one upstream sources?
I tried the following UPSTREAM_WORKSPACE
`"github:AprilRobotics/apriltag#master github:AprilRobotics/apriltag_ros#master github:stereolabs/zed-ros-wrapper#tags/v2.8.x"`

And it only loaded the first source

**Comment by ipa-mdl** [comment]
> Is it possible to have more than one upstream sources?

Yes, this should work.

Please check the output in the `setup_upstream_workspace` section.

**Comment by tianshiz** [comment]
ok my problem was i had quotes around, after removing the quotes it worked.
