### ISSUE TITLE
BEFORE_SCRIPT' is not used anymore. Please migrate to new hook system

### ISSUE THREAD

**Issue by tianshiz** [ros-industrial/industrial_ci#484]
I noticed that setting BEFORE_SCRIPT no longer works, what is the new hook system? I don't see it anywhere on the docs

**Comment by tianshiz** [comment]
never mind I was looking at the legacy docs it seems

**Comment by ipa-mdl** [comment]
For completeness:

The new system is explained in https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#customize-within-the-ci-process

The rationale for removing `BEFORE_SCRIPT` is given in https://github.com/ros-industrial/industrial_ci/blob/master/doc/migration_guide.md#before_script
