### ISSUE TITLE
How to disable cloning with submodules for UPSTREAM_WORKSPACE repository?

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial/industrial_ci#485]
I have a required upstream repository which has submodules. The submodules are thirdparty libraries and to speed up CI I have already installed them in a docker but cannot determine how to disable cloning with submodules for upstream repositories. Is is possible to disable cloning an upstream workspace repository with submodules?

Update: Using master branch of industrial_ci.

**Comment by ipa-mdl** [comment]
Recursive cloning was added in #443, without any opt-out.

Depending on your use case, I see two options:

- implement an opt-out
- remove the additional folders after the clone (prefix the paths with `-`)

**Comment by Levi-Armstrong** [comment]
The method for removing additional folders worked. Thank you.
