### ISSUE TITLE
Support Python formatting with Black

### ISSUE THREAD

**Issue by mortenfyhn** [ros-industrial/industrial_ci#487]
Hi yall and thank you for making this wonderful tool. I just recently discovered it (after having previously overlooked it because I was confused by the name). I'm testing it out now.

One thing I like to run in my pipelines is [Black](https://black.readthedocs.io/en/stable/) for Python code formatting. I see you have clang-format already supported. Are you open to supporting Black as well? I could probably attempt a PR.

**Comment by ipa-mdl** [comment]
> Are you open to supporting Black as well?

Yes, definitely.

>  I could probably attempt a PR.

If you do not need a ROS environment (I don't see why black would need one), it should work the same as for `clang-format`.
It might even make sense to have a common codebase.

**Comment by mortenfyhn** [comment]
Cool. Yeah, no ROS environment should be needed. I'm already running black checks outside of Industrial CI, before setting up and building any ROS stuff.
