### ISSUE TITLE
Travis/Bitbucket support

### ISSUE THREAD

**Issue by ipa-mdl** [ros-industrial/industrial_ci#497]
Travis announced Bitbucket integration: https://blog.travis-ci.com/2020-03-16-travis-ci-bitbucket-integration

I guess that `travis.sh` works for Bitbucket repositories as well, but this needs to be tested and documented.

**Comment by Briancbn** [comment]
All 3 branches of the industrial ci pass in Bitbucket using travis-ci. 
- The Bitbucket travis beta only are accessible through https://travis-ci.com, but not https://travis-ci.org
- The user and organization link is currently changed to https://travis-ci.org/bitbucket/profile/YOUR_GITHUB_ORGANIZATION and https://travis-ci.org/bitbucket/profile/YOUR_GITHUB_USER

master | legacy | legacy-transitional
|---|---|---|
[![Build Status](https://travis-ci.com/brian97cbn/industrial_ci.svg?branch=master)](https://travis-ci.com/bitbucket/brian97cbn/industrial_ci) | [![Build Status](https://travis-ci.com/brian97cbn/industrial_ci.svg?branch=legacy)](https://travis-ci.com/bitbucket/brian97cbn/industrial_ci) | [![Build Status](https://travis-ci.com/brian97cbn/industrial_ci.svg?branch=legacy_transitional)](https://travis-ci.com/bitbucket/brian97cbn/industrial_ci)
