### ISSUE TITLE
ROS Kinetic support

### ISSUE THREAD

**Issue by 130s** [ros-industrial/industrial_ci#51]
I see there are some interests (e.g. https://github.com/swri-robotics/mapviz/pull/358 @evenator). 

Looks like there's a way to run Xenial on Travis CI. https://github.com/travis-ci/travis-ci/issues/5821

I don't have an extra gear to add support for this any sooner, but PR is welcomed.

**Comment by evenator** [comment]
I'm working on a docker solution at the moment.

**Comment by 130s** [comment]
Addressed in #52 by @evenator
