### ISSUE TITLE
rerun_ci doesn't copy .ssh directory into docker

### ISSUE THREAD

**Issue by tylerjw** [ros-industrial/industrial_ci#523]
I need the copying of the ssh directory to get a key I need to checkout private repos inside the docker container.  run_ci does this but rerun_ci doesn't.

**Comment by tylerjw** [comment]
This doesn't matter because it seems that ssh-agent socket forwarding is working in rerun-ci so I can do this to verify that it is working:

`AFTER_INIT='echo $SSH_AUTH_SOCK && ssh-add -l'`

In run_ci I had to do this to get it to work:

`ADDITIONAL_DEBS="openssh-client" AFTER_INIT='eval $(ssh-agent -s) && ls ~/.ssh && ssh-add ~/.ssh/id_rsa'`

Maybe something is broken in `run_ci`?  If not, close this.

**Comment by ipa-mdl** [comment]
`HOME` was not passed as an environment, varibale so the keys folder could not be found..

**Comment by ipa-mdl** [comment]
To prevent the leak of SSH keys bunding the credentials will by an opt-in (#570)
