### ISSUE TITLE
unable to find ros-kinetic-ros-enviroment

### ISSUE THREAD

**Issue by tylerjw** [ros-industrial/industrial_ci#528]
This line:

industrial_ci/src/workspace.sh:231:        ici_apt_install "ros-$ROS_DISTRO-ros-environment"

Results in this error when run with ROS_DISTR=kinetic:

E: Unable to locate package ros-kinetic-ros-environment

This happens in the setup_rosdep step.

See:
https://travis-ci.com/github/ros-planning/moveit/jobs/347332243

**Comment by ipa-mdl** [comment]
You are trying to test (and install) kinetic packages in a melodic Docker image (`DOCKER_BASE_IMAGE="moveit/moveit:master-ci"`).
