### ISSUE TITLE
is bloom and binary release part of industrial_ci flow?

### ISSUE THREAD

**Issue by tianshiz** [ros-industrial/industrial_ci#535]
Or do I need to integrate rosbuildfarm somehow? I have a nice flow going with industrial_ci on my Bitbucket pipeline. Every pull request it performs build tests.

Is there a standard way to tie in industrial_ci, bloom and release all from the same Bitbucket pipelines?

**Comment by ipa-mdl** [comment]
This is [cross-post](https://answers.ros.org/question/355287/blooming-with-ros-industrial-ci-pipelines/), I will close it here in favor of ROS answers.
