### ISSUE TITLE
Is there support for switching compiler from gcc to clang?

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial/industrial_ci#538]
I am passing the following cmake args `-DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++` but I am also using ccache which looks like it is setting the environment variables CXX and CC to gcc.

**Comment by ipa-mdl** [comment]
Did you try setting `CC` and `CXX`?

**Comment by Levi-Armstrong** [comment]
I had not, but I will.

**Comment by ipa-mdl** [comment]
@Levi-Armstrong: Did setting `CC`  and `CXX` work?

**Comment by Levi-Armstrong** [comment]
It appears that setting `-DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++` does work.
