### ISSUE TITLE
Conditional rosdep keys in package.xml appear to break CI

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial/industrial_ci#546]
To support noetic builds it required upgrading a few package.xml to leverage conditionals because of python3 versus python2 and orocos_kdl switching to system version. Though when adding these conditionals to the package.xml the CI now fails on the `install_target_dependencies` but does not provide any information on why it failed.

https://github.com/ros-industrial-consortium/tesseract/pull/319

**Comment by ipa-mdl** [comment]
conditional rosdep keys in package.xml work properly, but perhaps not all of them..

**Comment by Levi-Armstrong** [comment]
The issue was on my end.
