### ISSUE TITLE
Sourcing target workspace setup.bash fails with 'COLCON_TRACE: unbound variable' error

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial/industrial_ci#585]
I have scheduled nightly builds and as of two days ago my CI build on focal for noetic started failing. I have the following line in my CI which is now failing with the `COLCON_TRACE: unbound variable` not sure what the issue is. Do you think this is related to CI or Colcon change?

```
BEFORE_RUN_TARGET_TEST_EMBED: "source /root/target_ws/install/setup.bash"
```

**Comment by gavanderhoorn** [comment]
Is this #581?

**Comment by Levi-Armstrong** [comment]
Ah, I will test the following to see if this resolves the issue.

```
BEFORE_RUN_TARGET_TEST_EMBED: "ici_with_unset_variables source /root/target_ws/install/setup.bash"
```

**Comment by Levi-Armstrong** [comment]
This solved the issue. @gavanderhoorn Thank you.
