### ISSUE TITLE
Cannot specify upstream workspace with SSH

### ISSUE THREAD

**Issue by stertingen** [ros-industrial/industrial_ci#593]
See: https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#workspace-management

I cannot specify a workspace like `UPSTREAM_WORKSPACE=git+ssh://git@gitlab.example.com/foo.git` because the `@` is interpreted as version indicator. The `@` symbol is needed to specify the SSH user in this case.

**Comment by ipa-mdl** [comment]
Thanks for reporting!
The parser needs to be patched.
In the meantime you could use a vcs (repos/rosinstall) file.

**Comment by ipa-mdl** [comment]
#596 removes the support for the ambiguous pip-style, please have a look.
