### ISSUE TITLE
[pylint] pylint check fails when no py files found

### ISSUE THREAD

**Issue by fmessmer** [ros-industrial/industrial_ci#620]
just found this in e.g. https://travis-ci.com/github/ipa320/cob_environments/builds/216901982

I'll try to fix this soon, until then I want it documented in this issue.

**Comment by ipa-mdl** [comment]
> I'll try to fix this soon, until then I want it documented in this issue.

Just wrap it with
```bash
if [ "${#files[@]}" -eq 0 ]; then
  .. existing code..
else
  ici_warn "No python files found, skipping pylint
fi
```

**Comment by fmessmer** [comment]
thanks for the suggested path: pr is #622
