### ISSUE TITLE
ROS1 noetic support for #!/usr/bin/env python

### ISSUE THREAD

**Issue by stwirth** [ros-industrial/industrial_ci#623]
I just tried to add a noetic build to flir_camera_driver: https://github.com/ros-drivers/flir_camera_driver/pull/67
That package uses a download script written in python to install a dependency.
The [Travis CI job](https://travis-ci.org/github/ros-drivers/flir_camera_driver/jobs/758689854) reports
```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Starting function 'build_target_workspace'
Starting >>> spinnaker_camera_driver
--- stderr: spinnaker_camera_driver
/usr/bin/env: ‘python’: No such file or directory
```
and then fails due to a missing include as the dependency was not downloaded.
I am assuming that the problem is that the default python executable on 20.04 is called `python3` and not `python`.
Maybe the build environment should have `python-is-python3` installed?

**Comment by gavanderhoorn** [comment]
isn't it actually the responsibility of the maintainer to change the shebang to `python3` explicitly, to signal that the script supports Python 3 and doesn't work with any other interpreter?

`python-is-python3` is a work-around, not a fix.

**Comment by stwirth** [comment]
The script works with python2 as well. But I agree, the script should be ported to python3 instead.

**Comment by gavanderhoorn** [comment]
You could use one of the hooks, or perhaps `ADDITIONAL_DEBS` to install `python-is-python3` at the appropriate time.

**Comment by ipa-mdl** [comment]
Normally, you should use `catkin_install_python` to avoid exactly this problem.
http://docs.ros.org/en/noetic/api/catkin/html/howto/format2/installing_python.html

**Comment by gavanderhoorn** [comment]
If it's a Catkin package, yes.

You could use that.

**Comment by stwirth** [comment]
The script in question runs during configuration time of cmake, so I would need to move it to another package. I made it use `#!/usr/bin/env python3` which works fine.

**Comment by stwirth** [comment]
(Using `ExternalProject_Add` in the `CMakeLists.txt` would probably be even better.)
