### ISSUE TITLE
What options are there for getting build artifacts out of the CI build?

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial/industrial_ci#637]
As part of the CI build I am currently leveraging CMake CPACK to Debians and NuGet packages but not sure how to get them back out such that you can leverage the GitHub actions for uploading artifacts.

**Comment by Levi-Armstrong** [comment]
I came up with a solution. Leveraging DOCKER_RUN_OPTS to map a different folder and AFTER_SCRIPT to copy the build artifacts to this mapped directory worked.

**Comment by ipa-mdl** [comment]
You can set `BASEDIR` to put all workspaces into that folder
