### ISSUE TITLE
Reduce verbosity?

### ISSUE THREAD

**Issue by davetcoleman** [ros-industrial/industrial_ci#66]
When using industrial_ci for MoveIt!'s many repos Travis is giving us the following warning:

> This log is too long to be displayed. Please reduce the verbosity of your build or download the raw log.

e.g. [here](https://travis-ci.org/davetcoleman/moveit/jobs/139272939). Any thoughts on how to optionally reduce output?

**Comment by 130s** [comment]
Yes this is a known issue.

There's a WIP https://github.com/ros-industrial/industrial_ci/pull/43 but as commented https://github.com/ros-industrial/industrial_ci/pull/43#issuecomment-223640058 the current approach isn't acceptable IMO.

I appreciate more ideas...

**Comment by 130s** [comment]
I guess we can close this after https://github.com/ros-industrial/industrial_ci/pull/94
