### ISSUE TITLE
UNDERLAY feature causes `build_upstream_workspace` to fail to find catkin CMake module

### ISSUE THREAD

**Issue by JStech** [ros-industrial/industrial_ci#668]
We attempted to use the UNDERLAY feature in MoveIt Calibration. It seemed to work [initially](https://github.com/ros-planning/moveit_calibration/actions/runs/683966589), but recently every CI run was failing in the `build_upstream_workspace` step with the error `The catkin CMake module was not found,...` (for instance, [here](https://github.com/ros-planning/moveit_calibration/runs/2387071599)). Reverting the use of the UNDERLAY feature fixed this error.

The error also occurred locally, when running this command:
```
rosrun industrial_ci rerun_ci src/moveit_calibration \
  ROS_DISTRO=melodic ROS_REPO=ros \
  DOCKER_IMAGE='moveit/moveit:melodic-source' \
  UPSTREAM_WORKSPACE='upstream.rosinstall' \
  BEFORE_INSTALL_UPSTREAM_DEPENDENCIES_EMBED='set +u && source /root/ws_moveit/install/setup.bash && set -u' \
  AFTER_RUN_TARGET_TEST='./.ci.prepare_codecov' \
  TARGET_CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS='--coverage' -DCMAKE_CXX_FLAGS='--coverage'" \
  ADDITIONAL_DEBS='lcov' \
  CCACHE_DIR="${HOME}/.ccache" \
  BASEDIR=${HOME}/.work
```

**Comment by fmessmer** [comment]
I guess, I intended UNDERLAY to be used **instead** of UPSTREAM_WORKSPACE in https://github.com/ros-industrial/industrial_ci/pull/609

I haven't looked into how both could be made to work together...

**Comment by gavanderhoorn** [comment]
It seems something isn't entirely correct in the environment setup:

> WARNING: Your workspace is not extending any other result space, but it is set to use a `linked` devel space layout. This requires the `catkin` CMake package in your source space in order to be built.

**Comment by JStech** [comment]
Tagging @tylerjw because he's much more familiar with MoveIt's use of `industrial_ci` than I am.

**Comment by ipa-mdl** [comment]
> I haven't looked into how both could be made to work together...

This should not be a problem..

> It seems something isn't entirely correct in the environment setup:

I had similar issues in some tests, but I don't recall why I got this error message.

**Comment by ipa-mdl** [comment]
@JStech: `UNDERLAY: /root/ws_moveit` does not point to the install (or devel) space.

https://github.com/ipa-mdl/moveit_calibration/tree/test/underlay seems to work.

The documentation needs to be improved and we should check if `setup.bash` is present.
Another option would be to check `$UNDERLAY/install` as well, but I would prefer the explicit configuration.

@fmessmer, @JStech , @tylerjw: What do you think?

**Comment by tylerjw** [comment]
Ah, I misunderstood how to use this feature.  @JStech if you set it to `UNDERLAY: /root/ws_moveit/install` as @ipa-hsd did in his branch that should work.
