### ISSUE TITLE
Travis errors without printing errors

### ISSUE THREAD

**Issue by 130s** [ros-industrial/industrial_ci#69]
Recently I've started seeing this here and there. The following is a typical last lines of a failing job.

https://travis-ci.org/ros-planning/moveit_core/jobs/141112595#L3741

```
++ travis_time_end
++ set +x
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Function setup_rosws took 0 min 0 sec
++ travis_time_start before_script
++ set +x     <-- End of the lines.
```

Also seen at https://travis-ci.org/ros-planning/moveit_core/jobs/141112594#L3940

Seen on both firefox, Chrome on multiple hosts.

**Comment by ipa-mdl** [comment]
This is resolved.
