### ISSUE TITLE
Non-default compilers (CMAKE_CXX_COMPILER)

### ISSUE THREAD

**Issue by wxmerkt** [ros-industrial/industrial_ci#692]
Hi,
I searched the documentation/codebase but could not find an answer: Is it currently possible to use non-gcc/default compilers by setting an option? E.g. if I want a package to build with clang instead of gcc (`CMAKE_C_COMPILER=clang`, `CMAKE_CXX_COMPILER=clang++`)?

Many thanks for your insights :-)

**Comment by ipa-mdl** [comment]
>  it currently possible to use non-gcc/default compilers by setting an option?

Yes, just set `CC` /`CXX` and install clang in `ADDITIONAL_DEBS` (if not part of your base image).

Instead of `CC`/`CXX`, you could set `CMAKE_ARGS` with your config as well, but IMHO `CC` and `CXX` are a little bit simpler to use and work with other build tools (than cmake).
