### ISSUE TITLE
failure not reported correctly 

### ISSUE THREAD

**Issue by rhaschke** [ros-industrial/industrial_ci#741]
In [this CI build](https://github.com/ubi-agni/moveit/runs/3428653136?check_suite_focus=true) a failure of `catkin build` in step `build_target_workspace` isn't correctly detected. I'm afraid that `ici_cmd` ignores the non-zero exit code of its command.

**Comment by ipa-mdl** [comment]
I just tried it locally. `catkin build` seems to return 0 in this case.

**Comment by ipa-mdl** [comment]
> I just tried it locally. catkin build seems to return 0 in this case.

`catkin build && echo "success"` in a workspace with only the target repo at the given commit:
```
[build] Error: The workspace packages have a circular dependency, and cannot be built. Please run `catkin list --deps` to determine the problematic package(s).
success
```

**Comment by rhaschke** [comment]
Hm. I tried as well, of course, and it returned 1 for me. 
```
$ catkin build; echo $?
...
[build] Circular dependency detected in the following packages: moveit_core, moveit_ros_occupancy_map_monitor, moveit_ros_planning
1
```

Obviously, Melodic and Noetic use different versions of catkin. In Noetic, one is correctly returned to indicate the error.
I'm closing the issue, as the underlying issue is with catkin obviously. Sorry for the noise.

**Comment by gavanderhoorn** [comment]
As it's released through `pip` as well: perhaps `pip install catkin_tools` for the Melodic build?
