### ISSUE TITLE
Depending on non-debian python packages

### ISSUE THREAD

**Issue by ardabbour** [ros-industrial/industrial_ci#769]
According to [this issue](https://github.com/ros-infrastructure/rosdep/issues/497), it is impossible to depend on a python package that is not a debian package through `rosdep`. Is there a way to inject a script to run within the CI agent; something like `pip install -r requirements.txt` after or during the upstream dependencies stage?

**Comment by mathias-luedtke** [comment]
>  it is impossible to depend on a python package that is not a debian package through rosdep

You can install a pip package, if it is defined in [rosdep db](https://github.com/ros/rosdistro/blob/master/rosdep/python.yaml) (`*-pip` suffix by convention)

>  Is there a way to inject a script to run within the CI agent; something like pip install -r requirements.txt after or during the upstream dependencies stage?

[Yes](https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#customize-within-the-ci-process)
