### ISSUE TITLE
Tests passes locally but fails during ci - ros industrial

### ISSUE THREAD

**Issue by kev4node** [ros-industrial/industrial_ci#771]
Hey, 
I am having an issue where our tests are passing locally but most of the tests fail during ci after a minor change. The tests that pass are also dependent on this change. Is there anyway to debug the tests results while using ros industrial ci as it would be possible when running the test in shell?

**Comment by Briancbn** [comment]
Checkout https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#run-industrial-ci-on-local-host. It will also be helpful if you can share some terminal output and your CI configuration.

**Comment by kev4node** [comment]
thank you.. The problem is fixed... the documentation really helped
