### ISSUE TITLE
Using rosinstall file from repository on private server

### ISSUE THREAD

**Issue by ipa-dmo** [ros-industrial/industrial_ci#781]
Hi everyone,

i would like to create a downstream workspace from a repository on a private server and the rosinstall file in that remote repository.
Is that possible and if so how would the correct syntax look like?

Alternatively i would just add the repository from the private server and have a duplicate of the rosinstall file from this remote private repository in my target repository and include it from there. This setup does work, but the first approach would be nicer regarding the extra effort to keep both rosinstall files up-to-date. (Especially when using this setup for several target workspaces and the same downstream workspace)

**Comment by mathias-luedtke** [comment]
> Is that possible

Yes.

> if so how would the correct syntax look like?

Really depends on your server and configuration.

Please have a look at https://github.com/ros-industrial/industrial_ci/issues/574#issuecomment-766706003 and https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#gitlab-ci-access-to-private-repositories

---
This issue tracker is meant for tracking bug and features. For general support please try https://answers.ros.org/.
I will close this issue now.
