### ISSUE TITLE
How to skip rosdep install from all workspaces?

### ISSUE THREAD

**Issue by sisaha9** [ros-industrial/industrial_ci#801]
I have a container through which I have already cached these installs. Additionally, as we are using other open source repository workspaces I don't want to install all the rosdeps. For example [Autoware](https://github.com/autowarefoundation/autoware) which has it's own large sets of dependencies. We don't want to add all of them as we only depend on a few packages from their repo

**Comment by mathias-luedtke** [comment]
You can set `ROSDEP_SKIP_KEYS`, as documented in https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#variables-you-can-configure
