### ISSUE TITLE
Failing because of inter-package dependencies

### ISSUE THREAD

**Issue by augustelalande** [ros-industrial/industrial_ci#841]
For example, in the case below both `do_stuff.py` and `test_do_stuff.py` have a dependency on `do_stuff_msgs.msg.Stuff`, leading to a test failure.

`ModuleNotFoundError: No module named 'do_stuff_msgs'`

Locally, I can resolve this by sourcing `install/setup.bash` before running `colcon test`, but I'm not sure how to do this with the industrial_ci. I have tried sourcing in `BEFORE_RUN_TARGET_TEST `and `BEFORE_RUN_TARGET_TEST_EMBED`, but that led to other errors.

```
src
├── do_stuff
│   ├── do_stuff
│   │    └── do_stuff.py
│   ├── package.xml
│   ├── setup.py
│   └── test
│        └── test_do_stuff.py
└──  do_stuff_msgs
    ├── CMakeLists.txt
    ├── msg
    │   └── Stuff.msg
    └── package.xml

```

I would appreciate any help.

**Comment by mathias-luedtke** [comment]
This sound like a missing `test_depend` in do_stuff's package.xml
I doubt that there is anything wrong with industrial_ci itself.
