### ISSUE TITLE
Install Python Packages System-wide for Python > 3.10

### ISSUE THREAD

**Issue by danthony06** [ros-industrial/industrial_ci#881]
https://github.com/ros-industrial/industrial_ci/pull/880 addresses problems with `rosdep`, `pip`, and Python versions newer than 3.10. Installing pure Python dependencies with `rosdep` is broken with Python 3.11 and above because `pip` will not install into the system-wide Python location without extra configuration. For more information on this, see the links at the end of this issue.

https://discourse.ros.org/t/rosdep-for-pip-is-broken-on-jazzy/38981/8
https://github.com/ros-infrastructure/rosdep/blob/f6857691e9a23e3a3f39e55189195dc3e4bf0770/doc/pip_and_pep_668.rst

**Comment by mathias-luedtke** [comment]
#885 allows settings `PIP_BREAK_SYSTEM_PACKAGES` more conveniently.
I do not want to set it by default for now.
