### ISSUE TITLE
manifest.xml support needed?

### ISSUE THREAD

**Issue by ipa-mdl** [ros-industrial/industrial_ci#97]
(from https://github.com/ros-industrial/industrial_ci/pull/95#issuecomment-272205293)

`catkin` and `rosdep` prefer `manifest.xml` over `package.xml` in hybrid packages.
`rosdep` works at least for external dependencies. `catkin` falls back to `rosbuild`, which fails because it is not setup properly.

I guess the only reasonable fix is to delete all `manifest.xml` files and print a warning.
However, I don't even know if someone really keeps `manifest.xml` files around..

**Comment by 130s** [comment]
>  However, I don't even know if someone really keeps manifest.xml files around..

Same thoughts here, and removed `bug` label.

**Comment by ipa-mdl** [comment]
looks like this is not needed.
